season31/urls.py
from django.conf.urls import url
from django.views.decorators.cache import never_cache
from django.views.generic import TemplateView

from . import views

urlpatterns = [
	url(r'^$', TemplateView.as_view(template_name="season31/index.html"), name='index'),
	url(r'^leaderboard/$', never_cache(views.LeaderboardView.as_view()), name='leaderboard'),
	url(r'^castaways/$', views.CastawaysView.as_view(), name='castaways'),
	url(r'^players/$', views.PlayersView.as_view(), name='players'),
	url(r'^episodes/$', views.EpisodesView.as_view(), name='episodes'),
	url(r'^actions/$', views.ActionsView.as_view(), name='actions'),
	url(r'^rules/', TemplateView.as_view(template_name="season31/rules.html"), name='rules'),
	url(r'^info/', TemplateView.as_view(template_name="season31/info.html"), name='info'),
	url(r'^player/(?P<pk>[0-9]+)/$', views.PlayerView.as_view(), name='player'),
	url(r'^player/(?P<pk>[0-9]+)/jsps/$', views.PlayerJSPView.as_view(), name='playerjsps'),
	url(r'^castaway/(?P<pk>[0-9]+)/$', views.CastawayView.as_view(), name='castaway'),
	url(r'^episode/(?P<pk>[0-9]+)/$', never_cache(views.EpisodeView.as_view()), name='episode'),
	url(r'^episode/(?P<pk>[0-9]+)/jsps/$', views.EpisodeJSPView.as_view(), name='episodejsps'),
	url(r'^updatescores/$', views.updatescores, name='updatescores'),
	url(r'^addepisode/$', views.addepisode, name='addepisode'),
	url(r'^tallyalljsps/$', views.tallyalljsps, name='tallyalljsps'),
	url(r'^backfillteams/$', views.backfillteams, name='backfillteams'),
	url(r'^playerrolloverteam/(?P<pe_id>[0-9]+)/$', views.playerrolloverteam, name='playerrolloverteam'),
	url(r'^pickteams/(?P<pe_id>[0-9]+)/$', views.pickteams, name='pickteams'),
	url(r'^pickvotes/(?P<pe_id>[0-9]+)/$', views.pickvotes, name='pickvotes'),
	url(r'^updateceactions/(?P<e_id>[0-9]+)/$', views.updateceactions, name='updateceactions'),
	url(r'^updatecevotes/(?P<e_id>[0-9]+)/$', views.updatecevotes, name='updatecevotes'),
	url(r'^rolloverepisodeteams/(?P<e_id>[0-9]+)/$', views.rolloverepisodeteams, name='rolloverepisodeteams'),
	url(r'^updateepisodescore/(?P<e_id>[0-9]+)/$', views.updateepisodescore, name='updateepisodescore'),
	url(r'^unlockepisode/(?P<e_id>[0-9]+)/$', views.unlockepisode, name='unlockepisode'),
	url(r'^updatecetribes/(?P<e_id>[0-9]+)/$', views.updatecetribes, name='updatecetribes'),
	url(r'^addcastaway/$', views.addcastaway, name='addcastaway'),
	url(r'^deletecastaway/$', views.deletecastaway, name='deletecastaway'),
	url(r'^addtribe/$', views.addtribe, name='addtribe'),
	url(r'^deletetribe/$', views.deletetribe, name='deletetribe'),
	url(r'^addaction/$', views.addaction, name='addaction'),
	url(r'^deleteaction/$', views.deleteaction, name='deleteaction'),
	url(r'^deleteepisode/(?P<e_id>[0-9]+)/$', views.deleteepisode, name='deleteepisode'),
	url(r'^togglehelptext/(?P<p_id>[0-9]+)/$', views.togglehelptext, name='togglehelptext'),
	url(r'^updateepisodetitle/(?P<e_id>[0-9]+)/$', views.updateepisodetitle, name='updateepisodetitle'),
	url(r'^updateepisodedatetime/(?P<e_id>[0-9]+)/$', views.updateepisodedatetime, name='updateepisodedatetime'),
	url(r'^updateepisodeteamsize/(?P<e_id>[0-9]+)/$', views.updateepisodeteamsize, name='updateepisodeteamsize'),
	url(r'^togglescorejsps/(?P<e_id>[0-9]+)/$', views.togglescorejsps, name='togglescorejsps'),
	url(r'^tallyepisodejsps/(?P<e_id>[0-9]+)/$', views.tallyepisodejsps, name='tallyepisodejsps'),
	url(r'^updatecastawayplace/(?P<c_id>[0-9]+)/$', views.updatecastawayplace, name='updatecastawayplace'),
	url(r'^updatecastawayname/(?P<c_id>[0-9]+)/$', views.updatecastawayname, name='updatecastawayname'),
	url(r'^register/$', views.register, name='register'),
	url(r'^login/$', views.user_login, name='login'),
	url(r'^logout/$', views.user_logout, name='logout'),
	url(r'^forgotpassword/$', views.user_forgotpassword, name='forgotpassword'),
	url(r'^resetpassword/(?P<p_id>[0-9]+)/$', views.resetpassword, name='resetpassword'),
	url(r'^toggleplayerpaidstatus/(?P<p_id>[0-9]+)/$', views.toggleplayerpaidstatus, name='toggleplayerpaidstatus'),
]

survivor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	url(r'^season31/', include('season31.urls', namespace="season31")),
	url(r'^$', lambda r: HttpResponseRedirect('season31/')),
]

season31/models.py
from datetime import datetime
from pytz import timezone
import logging
import pytz

from django.contrib.auth.models import User
from django.db import models

class Castaway(models.Model):
	name = models.CharField(max_length = 32)
	full_name = models.CharField(max_length = 32)
	age = models.PositiveIntegerField(default = 0)
	occupation = models.CharField(max_length = 32)
	tribe_name = models.CharField(max_length = 16)
	place = models.PositiveIntegerField(default = 0)
	out_episode_number = models.PositiveIntegerField(default = 0)
	def __unicode__(self):
		return self.name
	def get_tribe(self):
		tribe = self.castawayepisode_set.latest().tribe
		if tribe.name != self.tribe_name:
			self.tribe_name = tribe.name
			self.save()
		return tribe
	def get_first_initial(self):
		return self.name[0]
	def voted_out(self):
		if self.out_episode_number > 0:
			return True
		else:
			return False
	class Meta:
		ordering = ('place','tribe_name','name',)

class Player(models.Model):
	user = models.OneToOneField(User)
	username = models.CharField(max_length = 32, default = "")
	paid = models.BooleanField(default = False)
	hidden = models.BooleanField(default = False)
	show_help_text = models.BooleanField(default = True)
	forgot_password = models.BooleanField(default = False)
	def __unicode__(self):
		return self.user.username
	def get_full_name(self):
		return '%s %s' % (self.user.first_name, self.user.last_name)
	def get_latest_player_episode(self):
		return PlayerEpisode.objects.filter(player = self).latest()
	def get_latest_episode(self):
		try:
			latestepisode = Episode.objects.filter(is_locked = True).latest()
		except:
			latestepisode = None;
		return latestepisode
	def get_next_episode(self):
		try:
			nextepisode = Episode.objects.filter(is_locked = False).latest()
		except:
			nextepisode = None;
		return nextepisode
	class Meta:
		ordering = ('username',)

class Tribe(models.Model):
	name = models.CharField(max_length = 16)
	color = models.CharField(max_length = 16)
	def __unicode__(self):
		return self.name
	def get_all_episodes(self):
		return get_all_episodes()
	class Meta:
		ordering = ('name',)

class Action(models.Model):
	name = models.CharField(max_length = 32)
	score = models.IntegerField(default = 1)
	icon_filename = models.CharField(max_length = 32)
	description = models.CharField(max_length = 64)
	def __unicode__(self):
		return self.name
	class Meta:
		ordering = ('-score','name',)

class Episode(models.Model):
	title = models.CharField(max_length = 64)
	number = models.PositiveIntegerField(default = 0)
	air_date = models.DateTimeField()
	players = models.ManyToManyField(Player, through = 'PlayerEpisode', through_fields = ('episode', 'player'))
	castaways = models.ManyToManyField(Castaway, through = 'CastawayEpisode', through_fields = ('episode', 'castaway'))
	team_size = models.PositiveIntegerField(default = 5)
	is_locked = models.BooleanField(default = False)
	score_jsps = models.BooleanField(default = False)
	def __unicode__(self):
		return "Episode %i" % (self.number)
	def get_playerepisodes(self):
		return PlayerEpisode.objects.filter(player__hidden = False, episode = self).order_by('-total_score')
	def update_scores(self):
		return update_scores()
	def get_prev_episode(self):
		try:
			prev_e = Episode.objects.get(number = self.number - 1)
		except:
			prev_e = None
		return prev_e
	def get_next_episode(self):
		try:
			next_e = Episode.objects.get(number = self.number + 1)
		except:
			next_e = None
		return next_e
	def short(self):
		return "E%s" % ("{0:02d}".format(self.number))
	def air_day(self):
		weekdays = {0: "Sunday",1: "Monday",2: "Tuesday",3: "Wednesday",4: "Thursday",5: "Friday",6: "Saturday",}
		return weekdays.get(self.air_date.weekday(),"ERROR")
	def check_lock(self):
		if self.is_locked:
			return True
		est = timezone('US/Eastern')
		if datetime.now(est) > self.air_date:
			self.is_locked = True
			self.save()
			return True
		return False
	def seconds_to_lock(self):
		est = timezone('US/Eastern')
		if self.is_locked:
			return "Locked"
		timedelta = self.air_date - datetime.now(est)
		return (timedelta.days * 86400) + timedelta.seconds;
	def time_to_lock(self):
		est = timezone('US/Eastern')
		if self.is_locked:
			return "Locked"
		timedelta = self.air_date - datetime.now(est)
		return "%id %ih %im " % (timedelta.days, timedelta.seconds//3600, (timedelta.seconds//60)%60)
	class Meta:
		ordering = ('number',)
		get_latest_by = 'air_date'

class PlayerEpisode(models.Model):
	player = models.ForeignKey(Player)
	episode = models.ForeignKey(Episode)
	loyalty_bonus = models.PositiveIntegerField(default = 0)
	action_score = models.IntegerField(default = 0)
	correctly_predicted_votes = models.PositiveIntegerField(default = 0)
	vote_off_score = models.PositiveIntegerField(default = 0)
	jsp_score = models.PositiveIntegerField(default = 0)
	week_score = models.IntegerField(default = 0)
	total_score = models.IntegerField(default = 0)
	movement = models.IntegerField(default = 0)
	place = models.PositiveIntegerField(default = 0)
	def __unicode__(self):
		return "%s | %s" % (self.player.user.username, self.episode)
	def get_team_picks(self):
		return TeamPick.objects.filter(episode = self.episode, player = self.player)
	def get_vote_picks(self):
		return VotePick.objects.filter(episode = self.episode, player = self.player)
	def clear_team_picks(self):
		for pick in self.get_team_picks():
			pick.delete()
	def clear_vote_picks(self):
		for pick in self.get_vote_picks():
			pick.delete()
	def get_pick_options(self):
		return CastawayEpisode.objects.filter(episode = Episode.objects.latest())
	def replicate_picks(self):
		for pick in get_team_picks():
			print pick
	def score_lbs(self):
		try:
			lastplayerepisode = PlayerEpisode.objects.get(player = self.player, episode = Episode.objects.get(number = self.episode.number - 1))
		except:
			lastplayerepisode = None
		self.loyalty_bonus = 0
		if lastplayerepisode:
			for pick in self.get_team_picks():
				for last_pick in lastplayerepisode.get_team_picks():
					if pick.castaway == last_pick.castaway:
						self.loyalty_bonus += 1
						break
		self.save()
	def score_actions(self):
		self.action_score = 0
		for pick in self.get_team_picks():
			castawayepisode = pick.castaway_episode()
			if castawayepisode:
				self.action_score += castawayepisode.score
		self.save()
	def score_votes(self):
		self.correctly_predicted_votes = 0
		for pick in self.get_vote_picks():
			try:
				vo_action = pick.castaway_episode().actions.filter(name = "Out") # TODO: dont hardcode this name
			except:
				vo_action = None
			if vo_action:
				self.correctly_predicted_votes += 1
		self.vote_off_score = self.correctly_predicted_votes * 10 # TODO: dont hardcode this score
		self.save()
	def score_jsps(self):
		if not self.episode.score_jsps:
			return
		self.jsp_score = 0
		survivingcastaways = Castaway.objects.filter(out_episode_number = 0)
		pastepisodes = Episode.objects.filter(number__lte = self.episode.number)
		pastteampicks = TeamPick.objects.filter(castaway__in = survivingcastaways, episode__in = pastepisodes, player = self.player)
		if(self.episode.title != "Reunion"):
			self.jsp_score = pastteampicks.count()
		else:
			self.jsp_score = pastteampicks.count() * 2
		self.save()
	def update_score(self):
		try:
			lastplayerepisode = PlayerEpisode.objects.get(player = self.player, episode = Episode.objects.get(number = self.episode.number - 1))
		except:
			lastplayerepisode = None
		if lastplayerepisode:
			self.total_score = lastplayerepisode.total_score
		else:
			self.total_score = 0
		self.week_score = 0
		self.week_score = self.action_score + self.vote_off_score + self.jsp_score + self.loyalty_bonus
		self.total_score += self.week_score
		self.save()
	class Meta:
		ordering = ('episode', 'player')
		get_latest_by = 'episode'

class CastawayEpisode(models.Model):
	castaway = models.ForeignKey(Castaway)
	episode = models.ForeignKey(Episode)
	tribe = models.ForeignKey(Tribe)
	actions = models.ManyToManyField(Action, blank = True)
	score = models.IntegerField(default = 0)
	def __unicode__(self):
		return "%s | %s" % (self.castaway.name, self.episode)
	def update_score(self):
		self.score = 0
		for action in self.actions.all():
			self.score += action.score
		self.save()
	def out_this_episode(self):
		if self.castaway.out_episode_number == self.episode.number:
			return True
		return False
	class Meta:
		ordering = ('episode', 'tribe', '-score', 'castaway')
		get_latest_by = 'episode'

class TeamPick(models.Model):
	episode = models.ForeignKey(Episode)
	player = models.ForeignKey(Player)
	castaway = models.ForeignKey(Castaway)
	jsp_score = models.PositiveIntegerField(default = 0)
	def __unicode__(self):
		return "%s | %s | %s | Team Pick" % (self.episode.short(), self.player.user.username, self.castaway.name)
	def castaway_episode(self):
		try:
			castawayepisode = CastawayEpisode.objects.get(castaway = self.castaway, episode = self.episode)
		except:
			castawayepisode = None
		return castawayepisode
	def player_episode(self):
		try:
			playerepisode = PlayerEpisode.objects.get(player = self.player, episode = self.episode)
		except:
			playerepisode = None
		return playerepisode
	def out_this_episode(self):
		if self.castaway.out_episode_number == self.episode.number:
			return True
		return False
	def out_ever(self):
		if self.castaway.out_episode_number > 0:
			return True
		return False
	class Meta:
		ordering = ('episode', 'player', 'castaway')

class VotePick(models.Model):
	episode = models.ForeignKey(Episode)
	player = models.ForeignKey(Player)
	castaway = models.ForeignKey(Castaway)
	def __unicode__(self):
		return "%s | %s | %s | Team Pick" % (self.episode.short(), self.player.user.username, self.castaway.name)
	def castaway_episode(self):
		try:
			castawayepisode = CastawayEpisode.objects.get(castaway = self.castaway, episode = self.episode)
		except:
			castawayepisode = None
		return castawayepisode
	def player_episode(self):
		try:

season31/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password')

season31/templates/season31/episode.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'season31/style.css' %}" />

<table class="noborder"><tr>

	<td class="menu noborder texttop">
		{% include "season31/menu.html" %}
	</td>
	<td class="content noborder texttop textleft">

		<div class="textitalic">
			{% for se in simpleepisodes %}
			{% if se.number == simpleepisode.number %}
			<span class="textbold fgdarkgrey">{{ se.short }}</span>
			{% else %}
			<a href="{% url 'season31:episode' se.id %}" class="fggrey">{{ se.short }}</a>
			{% endif %}
			{% endfor %}
		</div>
		<div class="title">"{{ simpleepisode.title }}"</div>
		<div class="subtitle">{{ simpleepisode.air_day}}, {{ simpleepisode.air_date}} ET</div>

		<div class="spacer"></div>

		<!-- Castaway Table -->

		<div class="bgdarkgrey rounded pad2 datashow">
			<div class="textleft fglightgrey font24 pad4 rounded marg1">Castaway Actions</div>
			<table class="textcenter">
				<tr>
					<td class="bgblack padlr2"></td>
					<td class="bgblack padlr2"><a href="{% url 'season31:actions' %}" class="fgwhite">Actions</a></td>
					<td class="bgblack padlr2 datahide fglightgrey">Tribe</td>
					<td class="bgblack padlr2 datahide fglightgrey">Votee</td>
					<td class="bgblack padlr2 fglightgrey">Pts.</td>
				</tr>
				{% for sce in simplecastawayepisodes %}
				<tr>
					<td class="bgblack padlr2 textright"><a href="{% url 'season31:castaway' sce.castawayid %}" class="fg{{ sce.color }}">{{ sce.castawayname }}</a></td>
					<td class="bgblack padlr2">
					{% for sa in sce.actions %}
						<img src="{% static 'season31/images/icons/'%}{{ sa.icon_filename }}.png" title="{{ sa.name }}:
{{ sa.score }} Point(s)
{{ sa.description }}" />
					{% endfor %}
					</td>
					<td class="bgblack padlr2 datahide bg{{ sce.color }}">{{ sce.tribe }}</td>
					{% if sce.vote %}
					<td class="bgblack padlr2 datahide bg{{ sce.vote.color }}"><a href="{% url 'season31:castaway' sce.vote.id %}">{{ sce.vote.name }}</a></td>
					{% else %}
					<td class="bgblack padlr2 datahide">-</td>
					{% endif %}
					<td class="bgwhite padlr2">{{ sce.score }}</td>
				</tr>
				{% endfor %}
			</table>
		</div>

		<div class="spacer"></div>
	
	<!-- Uncomment to make tables side by side instead of top and bottom
	</td>
	<td class="content noborder texttop textleft">
	-->

		{% if user.player.show_help_text %}
			<div class="pad4 textright">
				Mouseover column headers for their full names.
			</div>
		{% endif %}
		<!-- Player Table -->
		<div class="bgdarkgrey rounded pad2">
			<div class="textleft fglightgrey font24 pad4 rounded marg1">Player Points</div>
			<table class="textcenter">
				<tr>
					<td class="bgblack parlr2"></td>
					<td class="bgblack padlr2 fggreen4">Team Members</td>
					<td class="bgblack padlr2 fgred4">Vote Off Picks</td>
					<td class="bgblack padlr2 fglightgrey" title="Loyalty Bonus Points">LB</td>
					<td class="bgblack padlr2 fggreen4" title="Team Action Points">TA</td>
					<td class="bgblack padlr2 fgred4" title="Vote-Off Prediction Points">VO</td>
					<td class="bgblack parlr2 fglightgrey" title="Jury Survivor Points">JSP</td>
					<td class="bgblack parlr2 fglightgrey textbold" title="This Episode's Score">Week</td>
					<td class="bgblack parlr2 fglightgrey textbold" title="Total Score Score">Total</td>
				</tr>
				{% if not simpleepisode.is_locked %}
				<tr>
					<td colspan=14>Picks will be revealed in {{ episode.time_to_lock }}</td>
				</tr>
				{% else %}
				{% for spe in simpleplayerepisodes %}
				<tr>
					<td class="bgblack padlr2 textright">
						{% if spe.vote_off_score > 0 %}
							<img src="{% static 'season31/images/icons/'%}CorrectVote.png" class="actionsmall marglr4" title="Correctly Predicted Vote" />
						{% endif %}
						<a href="{% url 'season31:player' spe.playerid %}" class="fgwhite">{{ spe.playername }}</a>
					</td>

					<td class="bgblack padlr4">
						<table class="tablecenter noborder"><tr>
							{% for sp in spe.tpicks %}
							<td class="noborder padlr8 padtb2 marg0 bg{{sp.color}}">
								<a href="{% url 'season31:castaway' sp.id %}" class="fgblack">{{ sp.name }}</a>
							</td>
							{% endfor %}
						</tr></table>
					</td>
					<td class="bgblack padlr4">
						<table class="tablecenter noborder"><tr>
							{% for sp in spe.vpicks %}
							<td class="noborder padlr8 padtb2 marg0 bg{{sp.color}}">
								<a href="{% url 'season31:castaway' sp.id %}">{{ sp.name }}</a>
							</td>
							{% endfor %}
						</tr></table>
					</td>
					<td class="bglightgrey padlr2">{{ spe.loyalty_bonus }}</td>
					<td class="bglightgrey padlr2">{{ spe.action_score }}</td>
					<td class="bglightgrey padlr2">{{ spe.vote_off_score }}</td>
					<td class="bglightgrey padlr2">{{ spe.jsp_score }}</td>
					<td class="bgwhite padlr2 textbold">{{ spe.week_score }}</td>
					<td class="bgwhite padlr2 textbold">{{ spe.total_score }}</td>
				</tr>
				{% endfor %}
				{% endif %}
			</table>
		</div>

	</td>
	{% if user.is_superuser  %}
	<td class="bgadmin noborder texttop">
		<div class="bgdelete pad4 marg4">
			<form action="{% url 'season31:deleteepisode' simpleepisode.id %}" method="post">
				{% csrf_token %}
				<input type="checkbox" name="check1" id="check1" />
				<input type="submit" class="width60" value="Delete This Episode" />
				<input type="checkbox" name="check2" id="check2" />
			</form>
		</div>
		<div class="bgwhite pad4 marg4">
			<form action="{% url 'season31:updateepisodetitle' simpleepisode.id %}" method="post">
				{% csrf_token %}
				<input type="text" class="width50 textcenter" name="title" />
				<input type="submit" class="width40" value="Update Episode Title" />
			</form>
		</div>
		<div class="bgwhite pad4 marg4">
			<form action="{% url 'season31:updateepisodedatetime' simpleepisode.id %}" method="post">
				{% csrf_token %}
				<input type="text" class="width40 textcenter" name="airdatetime" value="YYYYmmdd HH"/>
				<input type="submit" class="width50" value="Update Air Date / Time" />
			</form>
		</div>
		<div class="bgwhite pad4 marg4">
			<form action="{% url 'season31:updateepisodeteamsize' simpleepisode.id %}" method="post">
				{% csrf_token %}
				<input type="number" class="width30 textcenter" name="teamsize" id="teamsize" min="2" max="10" value="{{ simpleepisode.team_size }}" />
				<input type="submit" class="width60" value="Update Team Size" />
			</form>
		</div>
		<div class="bgwhite pad4 marg4">
			<form action="{% url 'season31:rolloverepisodeteams' simpleepisode.id %}" method="post">
				{% csrf_token %}
				<input type="submit" class="width100" value="Rollover Episode Teams" />
			</form>
		</div>
		<div class="bgwhite pad4 marg4">
			<form action="{% url 'season31:updateepisodescore' simpleepisode.id %}" method="post">
				{% csrf_token %}
				<input type="submit" class="width100" value="Update Episode Score" />
			</form>
		</div>
		<div class="bgwhite pad4 marg4">
			<form action="{% url 'season31:togglescorejsps' simpleepisode.id %}" method="post">
				{% csrf_token %}
				<input type="submit" class="width100" value="JSPs {% if not simpleepisode.score_jsps %}NOT {% endif %}Scoring" />
			</form>
		</div>
		<div class="bgwhite pad4 marg4">
			<form action="{% url 'season31:tallyepisodejsps' simpleepisode.id %}" method="post">
				{% csrf_token %}
				<input type="submit" class="width100" value="Tally Episode JSPs" />
			</form>
		</div>
		{% if simpleepisode.is_locked %}
		<div class="bgwhite pad4 marg4">
			<form action="{% url 'season31:unlockepisode' simpleepisode.id %}" method="post">
				{% csrf_token %}
				<input type="submit" class="width100" value="Unlock Episode" />
			</form>
		</div>
		<table class="marg4">
			<tr>
				<td class="bgdarkgrey fgwhite textleft">Actions</td>
				<td class="bgdarkgrey fgwhite textleft">Votes</td>
				<td class="bgdarkgrey fgwhite textleft">Tribes</td>
			</tr>
			<tr>
				<td class="bgwhite textleft">
					<form action="{% url 'season31:updateceactions' simpleepisode.id %}" method="post">
						{% csrf_token %}
						<div class="fggrey">
							<input type="checkbox" name="delete" id="delete" />
							<label for="delete">Delete:</label>
						</div>
						<div class="pad0">
							<select name="action">
								{% for sa in simpleactions %}
								<option value="{{ sa.id }}">{{ sa.name }}</option>
								{% endfor %}
							</select>
						</div>
						{% for sce in simplecastawayepisodes %}
						<div class="pad0 fg{{ sce.color }}">
							<input type="checkbox" name="castaways" id="{{ sce.id }}" value="{{ sce.id }}" />
							<label for="{{ sce.id }}">{{ sce.castawayname }}</label>
						</div>
						{% endfor %}
						<input type="submit" value="Update Actions" />
					</form>
				</td>
				<td class="bgwhite textleft">
					<form action="{% url 'season31:updatecevotes' simpleepisode.id %}" method="post">
						{% csrf_token %}
						Votee:
						<div class="pad0">
							<select name="votee">
								{% for sce in simplecastawayepisodes %}
								<option value="{{ sce.castawayid }}">{{ sce.castawayname }}</option>
								{% endfor %}
							</select>
						</div>
						{% for sce in simplecastawayepisodes %}
						<div class="pad0 fg{{ sce.color }}">
							<input type="checkbox" name="voters" id="{{ sce.id }}" value="{{ sce.id }}" />
							<label for="{{ sce.id }}">{{ sce.castawayname }}</label>
						</div>
						{% endfor %}
						<div>
							<input type="submit" value="Update Votes" />
						</div>
					</form>
				</td>
				<td class="bgwhite textleft">
					<form action="{% url 'season31:updatecetribes' simpleepisode.id %}" method="post">
						{% csrf_token %}
						New Tribe:
						<div class="pad0">
							<select name="tribe">
								{% for st in simpletribes %}
								<option value="{{ st.id }}">{{ st.name }}</option>
								{% endfor %}
							</select>
						</div>
						{% for sce in simplecastawayepisodes %}
						<div class="pad0 fg{{ sce.color }}">
							<input type="checkbox" name="castaways" id="{{ sce.id }}" value="{{ sce.id }}" />
							<label for="{{ sce.id }}">{{ sce.castawayname }}</label>
						</div>
						{% endfor %}
						<div>
							<input type="submit" value="Update Tribes" />
						</div>
					</form>
				</td>
			</tr>
			{% endif %}
		</table>
		{% endif %}
		
	</td>
	
</tr></table>